---

galaxy_info:
  author: Mats Blomdahl
  description: Provision of Nginx reverse proxy

  license: Apache-2.0

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - nginx

dependencies: []

...
