---

- name: set timezone to europe/stockholm
  copy: src=/usr/share/zoneinfo/Europe/Stockholm dest=/etc/localtime
  tags: common

- name: install ntp
  yum: name=ntp state=present
  tags: common

- name: ntpd running and enabled
  service: name=ntpd state=started enabled=yes
  tags: common

- name: install firewalld
  yum: name=firewalld state=present
  tags: common

- name: firewalld running and enabled
  service: name=firewalld state=started enabled=yes
  tags: common

- name: epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    enabled: no
  tags: common

- name: install epel-release
  yum: name=epel-release state=present
  tags: common

- name: install htop, jq, python-pip etc from epel
  yum:
    name: ['htop', 'jq', 'python-pip', 'bash-completion-extras']
    enablerepo: epel
    state: present
  tags: common

- name: install pip-18.1
  pip: name=pip version=18.1 state=present
  tags: common

- name: ius repo
  yum_repository:
    name: ius
    description: IUS Community Packages for Enterprise Linux {{
                 ansible_distribution_major_version }} - $basearch
    mirrorlist: https://mirrors.iuscommunity.org/mirrorlist?repo=ius-centos{{
                ansible_distribution_major_version }}&arch=$basearch&protocol=http
    gpgkey: https://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    enabled: no
  tags: common

- name: install modern git version from ius
  yum: name=git2u enablerepo=ius state=present
  tags: common

- name: check for git-lfs
  shell: git lfs version
  register: check_git_lfs_version
  ignore_errors: yes
  changed_when: no
  tags: common

- block:
    - name: run git lfs install script
      shell: bash -ilc "curl -s
             https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash"
      tags: common

    - name: yum intall git-lfs
      shell: yum install -y git-lfs && git lfs install
      args:
        warn: no
      tags: common

  when: check_git_lfs_version is failed


- name: uninstall python-requests
  yum: name=python-requests state=absent
  tags: common

- name: configure sysadmin accounts
  user:
    name: "{{ item }}"
    groups: wheel
    state: present
    force: yes
  with_items: "{{ sysadmins }}"
  tags: common

- name: set ~/.ssh/authorized_keys for sysadmins
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', item + '_id_rsa.pub') }}"
    exclusive: yes
  with_items: "{{ sysadmins }}"
  tags: common

- name: disable password authentication and root login in sshd_config
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK common"
    block: |
      PermitRootLogin no
      Match Group wheel
      	PasswordAuthentication no
  register: sshd_config
  tags: common

- name: restart sshd to apply config changes
  service: name=sshd state=restarted
  when: sshd_config is changed
  tags: common

- name: remove ~/.ssh/authorized_keys for 'root' user
  file:
    path: /root/.ssh/authorized_keys
    state: absent
  tags: common

...
